WikiSummarizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

main/urls.py
from django.urls import path
from .views import home
app_name="main"
urlpatterns = [
    path("", home, name="home"),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.forms import Form, URLField, ChoiceField


class SummarizerForm(Form):
    SUMMARIZER_TYPE_CHOICES = (
        ('random', 'Random'),
        ('luhn', 'Luhn'),
        ('lsa', 'Latent Semantic Analysis'),
        # ('edmundson', 'Edmundson'),
        ('lexrank', 'LexRank'),
        ('textrank', 'TextRank'),
        ('sumbasic', 'SumBasic'),
        ('kl', 'KL-SUM')

    )
    wikipedia_url = URLField(max_length=5000, required=True, label="Wikipedia URL")
    summarizer_type = ChoiceField(choices=SUMMARIZER_TYPE_CHOICES, required=True, label="Summarizer Type")

main/views.py
from django.shortcuts import render
from .forms import SummarizerForm
from .summarizer import TextSummarizer
# Create your views here.


def home(request):
    form = SummarizerForm()
    if request.method == "POST":
        form = SummarizerForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['wikipedia_url']
            summarizer_type = form.cleaned_data['summarizer_type']
            summarizer = TextSummarizer(url, summarizer_type)
            summary = summarizer.get_summary()
            return render(request, 'home.html', {'form': form, 'is_result': True, 'result': summary})
    return render(request, 'home.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wiki Summarizer</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Wiki Summarizer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div class="container fluid" style="padding: 32px">
    <div class="row">
        <div class="col-6 mx-auto">
            <div class="card">
              <div class="card-header">
                Summarizer
              </div>
              <div class="card-body">
                  <form method="post" action="{% url 'main:home' %}">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-primary float-end">Process</button>
                    <button type="reset" class="btn btn-link float-end">Reset</button>
                  </form>
              </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 mx-auto">
            {% if is_result %}
            <div class="card" style="margin-top: 32px">
                <div class="card-header">
                    Result
                </div>
                <div class="card-body">
                    {{ result }}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{%  endblock %}